# Generated by Django 4.0.1 on 2022-01-12 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('departure_date', models.DateTimeField(auto_now_add=True)),
                ('num_adults', models.IntegerField()),
                ('num_kids', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(choices=[('STANDARD', 'standard'), ('PREMIUM', 'premium'), ('EXECUTIVE', 'executive'), ('ROYAL', 'royal')], max_length=20)),
                ('bed_type', models.CharField(choices=[('TWIN', 'twin'), ('QUEEN', 'queen'), ('KING', 'king')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
