# Generated by Django 4.0.1 on 2022-01-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bed_type',
            field=models.CharField(choices=[('TWIN', 'twin'), ('QUEEN', 'queen'), ('KING', 'king')], default='TWIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('STANDARD', 'standard'), ('PREMIUM', 'premium'), ('EXECUTIVE', 'executive'), ('ROYAL', 'royal')], default='STANDARD', max_length=20),
        ),
    ]
