# Generated by Django 4.0.1 on 2022-01-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_bed_type_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
