# Generated by Django 4.0.1 on 2022-01-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity_of_stay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
